service: product-service

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1
  environment:
    PG_HOST: ${self:custom.secrets.db.PG_HOST}
    PG_PORT: ${self:custom.secrets.db.PG_PORT}
    PG_DATABASE: ${self:custom.secrets.db.PG_DATABASE}
    PG_USERNAME: ${self:custom.secrets.db.PG_USERNAME}
    PG_PASSWORD: ${self:custom.secrets.db.PG_PASSWORD}

plugins:
  - serverless-webpack

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules:
      forceInclude:
        - pg
  secrets: ${file(secrets.yml)}

functions:
  getAllProducts:
    handler: handler.getAllProducts
    events:
      - http:
          path: products
          method: get
  getProductById:
    handler: handler.getProductById
    events:
      - http:
          path: products/{productId}
          method: get
  postProduct:
    handler: handler.postProduct
    events:
      - http:
          path: products
          method: post
